name: den.akifev
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: open dir
        run: cd $GITHUB_WORKSPACE/
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
            java-version: '11'
            distribution: 'adopt'
      - name: main_test
        run: java -classpath src:test/lib/* org.junit.runner.JUnitCore operationsTest.java
