name: den.akifev
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: open dir
        run: cd $GITHUB_WORKSPACE/
      - name: main_test
        run: java -classpath src:test/lib/* org.junit.runner.JUnitCore src/operationsTest.java
